version: "3"

services:
  image-optimizer:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - "./:/app"
      - "./node_modules:/app/node_modules:cached"
      # Configure your AWS account in ./aws/credentials and ./aws/credentials
      - "./aws:/root/.aws"
      # Or uncomment the line below to use your local AWS Cli config
      # - "~/.aws:/root/.aws"

